owner: wait-what
repo: uptime

sites:
  - name: Ruby
    url: https://files.waitwhat.sh/?
  - name: Miruku.cafe
    url: https://miruku.cafe/?
  - name: Autumn
    url: https://autumn.revolt.chat/?

status-website:
  cname: status.waitwhat.sh
  logoUrl: https://waitwhat.sh/favicon.png
  name: Uptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://waitwhat.sh/
